# Generated by Django 4.0.6 on 2022-07-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0010_assignment_issubmitted'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='allAssignments',
        ),
        migrations.AddField(
            model_name='member',
            name='allAssignments',
            field=models.ManyToManyField(blank=True, to='Grades.assignment'),
        ),
    ]
