# Generated by Django 4.0.6 on 2022-07-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_remove_student_allassignments_member_allassignments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coursephoto',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
