# Generated by Django 4.0.6 on 2022-07-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_course_coursephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='about',
            field=models.CharField(blank=True, default='Edit profile to view.', max_length=1000),
        ),
    ]
