# Generated by Django 4.0.6 on 2022-07-28 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0007_message_title'),
        ('Users', '0005_course_forum_member_messagelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='forum',
        ),
        migrations.AddField(
            model_name='course',
            name='forum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Messages.forum'),
        ),
    ]
