# Generated by Django 4.0.6 on 2022-07-28 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0008_message_uniquemsgno'),
        ('Users', '0006_remove_course_forum_course_forum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='messagelist',
        ),
        migrations.AddField(
            model_name='member',
            name='messagelist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Messages.forum'),
        ),
    ]
