# Generated by Django 4.0.6 on 2022-07-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_remove_member_messagelist_member_messagelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='coursebackground',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
