# Generated by Django 4.0.6 on 2022-07-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_alter_member_profilephoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryNo', models.CharField(max_length=12, unique=True)),
                ('fernetNo', models.CharField(max_length=100000)),
            ],
        ),
    ]
