# Generated by Django 4.0.6 on 2022-07-31 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_passwordmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordmodel',
            old_name='fernetNo',
            new_name='rsaNo',
        ),
    ]
