# Generated by Django 4.0.6 on 2022-07-31 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_rename_fernetno_passwordmodel_rsano'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordmodel',
            old_name='rsaNo',
            new_name='fernetNo',
        ),
    ]
