# Generated by Django 4.0.6 on 2022-07-13 09:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Quizzes', '0001_initial'),
        ('Documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('grade', models.CharField(choices=[('0', 'No Grade'), ('13', 'X / Project, PHD. Contd.'), ('12', 'Z / Course Contd.'), ('11', 'S / Satisfactory'), ('10', 'A'), ('9', 'A-'), ('8', 'B'), ('7', 'B-'), ('6', 'C'), ('5', 'C-'), ('4', 'D'), ('3', 'D-'), ('2', 'E'), ('1', 'E-'), ('-6', 'F'), ('-1', 'NP / AUDIT PASS'), ('-2', 'NF / AUDIT FAIL'), ('-3', 'I / INCOMPLETE'), ('-4', 'W / WITHDRAWAL'), ('-5', 'U / UNSATISFACTORY')], default='No Grade', max_length=2)),
                ('dateCreated', models.DateField(default=django.utils.timezone.now)),
                ('dateGraded', models.DateField()),
                ('dueDate', models.DateField()),
                ('totalMarks', models.IntegerField()),
                ('earntMarks', models.IntegerField()),
                ('notes', models.CharField(max_length=3000)),
                ('remarks', models.CharField(max_length=3000)),
                ('isQuiz', models.BooleanField(default=False)),
                ('courseCode', models.CharField(default='CODE', max_length=6)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizzes.quiz')),
                ('submission', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Documents.docs')),
            ],
        ),
    ]
