# Generated by Django 4.0.6 on 2022-07-13 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0001_initial'),
        ('Grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='dateGraded',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='dueDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='earntMarks',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='notes',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='quiz',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Quizzes.quiz'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='remarks',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='totalMarks',
            field=models.IntegerField(blank=True),
        ),
    ]
