# Generated by Django 4.0.6 on 2022-07-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0002_alter_assignment_dategraded_alter_assignment_duedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='dateGraded',
            field=models.DateField(blank=True, null=True),
        ),
    ]
