# Generated by Django 4.0.6 on 2022-07-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0003_alter_assignment_dategraded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='dueDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
