# Generated by Django 4.0.6 on 2022-07-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0007_alter_assignment_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='earntMarks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='totalMarks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
