# Generated by Django 4.0.6 on 2022-07-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0009_alter_assignment_notes_alter_assignment_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='isSubmitted',
            field=models.BooleanField(default=False),
        ),
    ]
