# Generated by Django 4.0.6 on 2022-07-13 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('uploadedBy', models.CharField(blank=True, default='None', max_length=12)),
                ('file', models.FileField(max_length=1000, upload_to='media/documents/')),
                ('uploadedDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
