# Generated by Django 4.0.6 on 2022-07-13 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QnImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mainimage', models.ImageField(upload_to='qnimgs')),
                ('uploadedOn', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnNo', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('qnData', models.CharField(max_length=10000)),
                ('answer', models.CharField(max_length=10000)),
                ('qnFigures', models.ManyToManyField(to='Quizzes.qnimagemodel')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('instructions', models.CharField(max_length=10000)),
                ('summarks', models.IntegerField()),
                ('listOfQns', models.ManyToManyField(to='Quizzes.question')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('startdatetime', models.DateField()),
                ('enddatetime', models.DateField()),
                ('duration', models.CharField(max_length=100)),
                ('instructions', models.CharField(max_length=10000)),
                ('maxmarks', models.IntegerField()),
                ('earntmarks', models.IntegerField()),
                ('listOfQnBanks', models.ManyToManyField(to='Quizzes.questionbank')),
            ],
        ),
    ]
