# Generated by Django 4.0.6 on 2022-07-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='qnData',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='question',
            name='qnFigures',
            field=models.ManyToManyField(blank=True, to='Quizzes.qnimagemodel'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qnNo',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='instructions',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='listOfQns',
            field=models.ManyToManyField(blank=True, to='Quizzes.question'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='summarks',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='earntmarks',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='enddatetime',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='instructions',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='listOfQnBanks',
            field=models.ManyToManyField(blank=True, to='Quizzes.questionbank'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='maxmarks',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='startdatetime',
            field=models.DateField(blank=True),
        ),
    ]
