# Generated by Django 4.0.6 on 2022-07-27 10:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0002_alter_question_answer_alter_question_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='enddatetime',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='startdatetime',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
