# Generated by Django 4.0.6 on 2022-07-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0003_alter_quiz_enddatetime_alter_quiz_startdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='earntmarks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='maxmarks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
