# Generated by Django 4.0.6 on 2022-07-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0005_alter_question_marks_alter_question_qnno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.TimeField(blank=True),
        ),
    ]
