# Generated by Django 4.0.6 on 2022-07-27 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0006_alter_quiz_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='enddatetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='startdatetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
