# Generated by Django 4.0.6 on 2022-07-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0007_alter_quiz_enddatetime_alter_quiz_startdatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='usrmarks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
