# Generated by Django 4.0.6 on 2022-07-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0002_message_nextmsg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forumMessages', models.ManyToManyField(blank=True, null=True, to='Messages.message')),
            ],
        ),
    ]
