# Generated by Django 4.0.6 on 2022-07-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0003_forum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='forumMessages',
            field=models.ManyToManyField(blank=True, to='Messages.message'),
        ),
    ]
