# Generated by Django 4.0.6 on 2022-07-28 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0004_alter_forum_forummessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='datetimesent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
