# Generated by Django 4.0.6 on 2022-07-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0005_message_datetimesent'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='name',
            field=models.CharField(blank=True, default='DefaultForum', max_length=100, unique=True),
        ),
    ]
