# Generated by Django 4.0.6 on 2022-07-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0006_forum_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.CharField(blank='True', default='#', max_length=300),
        ),
    ]
