# Generated by Django 4.0.6 on 2022-07-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0007_message_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='uniquemsgno',
            field=models.IntegerField(default=0),
        ),
    ]
